#!/bin/bash

NAME="tesi" # modificiare per scegliere il nome del file di origine (.tex)

echo -----------
echo - Pulizia -
echo -----------

if [[ $# -gt 1 ]] && [[ $1 == '-c' ]]; then
    ./clean -s
fi

echo --------------------
echo - Inizializzazione -
echo --------------------

pdflatex $NAME #-output-directory=$DIR $NAME
biber $NAME
makeindex -s ./$NAME.ist -t ./$NAME.glg -o ./$NAME.gls ./$NAME.glo
makeindex -s ./$NAME.ist -t ./$NAME.alg -o ./$NAME.acr ./$NAME.acn

# Due volte because Latex

pdflatex $NAME
biber $NAME
makeindex -s ./$NAME.ist -t ./$NAME.glg -o ./$NAME.gls ./$NAME.glo
makeindex -s ./$NAME.ist -t ./$NAME.alg -o ./$NAME.acr ./$NAME.acn

echo -------------------------
echo - Generazione Documento -
echo -------------------------

pdflatex $NAME
# pdflatex $NAME

echo -----------
echo - Pulizia -
echo -----------

if [[ $# -gt 1 ]] && [[ $1 == '-c' ]]; then
    ./clean -s
fi

# rm *.acn *.aux *.bbl *.bcf *.glo
# rm *.ist *.lof *.lot *.run.xml *.toc

# Per mantenere i log commentare la linea seguente
# rm *.blg  *.log


echo ---------------------------- END -----------------------------
